### ISSUE TITLE
Put bdk_file_store into bdk_chain

### ISSUE THREAD

**Issue by LLFourn** [LLFourn/bdk_core_staging#114]
It only needs `std` and `bincode v2.0.0`. We can make bincode an optional dependency as I think implementing bincode traits directly would be a nice addition anyway.

The only thing I can see that we need to do is get rid of `anyhow` from `bdk_file_persist` (just return an `std::io::Error`) and to actually implement the bincode traits on everything. Some things might have to be done without derive since we might want to use consensus encode/decode for various bitcoin types.

**Comment by evanlinjin** [comment]
I think it would be best to use `bincode` via `serde` for now, as `bitcoin` types do not implement `bincode::{Decode, Encode}` and will take some time to impl them for our structures.

**Comment by LLFourn** [comment]
Fixed by #115
