### ISSUE TITLE
Inflate_changeset must not produce a changeset that has conflicts

### ISSUE THREAD

**Issue by LLFourn** [LLFourn/bdk_core_staging#139]
When creating its changeset `inflate_changeset` checks for conflicts with its local chain but doesn't not check for conflicts within the changeset that it is inflating. This allows it to create a contradictory changeset which it should not do.

**Comment by evanlinjin** [comment]
One way to do this is to use an internal `TxGraph` and we add changeset transactions one by one and check for conflicts with each add.

**Comment by LLFourn** [comment]
This is already done. It doesn't do descendants eviction but that's a problem everywhere.

**Comment by evanlinjin** [comment]
> This is already done. It doesn't do descendants eviction but that's a problem everywhere.

#138 will change that! :wink:
