### ISSUE TITLE
Improve efficiency of `BnbLimit::Duration` 

### ISSUE THREAD

**Issue by evanlinjin** [LLFourn/bdk_core_staging#28]
As @afilini mentioned in https://github.com/LLFourn/bdk_core_staging/pull/23#discussion_r987839307

> post-merge note: i don't have real numbers but i'm guessing the syscall to get the current time can easily take 10x more time than just running a bnb iteration (due to the context switch), at least on modern cpus.
>
> i think it would make sense to check the time every n iterations, with n probably >= 100. worst case you overshoot a bit, but overall at least you'd spend most of the time actually doing work rather than waiting for a syscall to finish.
>
> there's a catch, though: if you have a very very slow cpu and a lot of utxos you may end up overshooting by a lot. i'm not sure what's the solution here though, i don't think it's worth adding the complexity to measure how long a few iterations take to adjust the n parameter. currently the bnb does i think thousands of iterations and nobody ever complained, so n = 100 i think is more than reasonable imho.

**Comment by LLFourn** [comment]
what is the reason for having the duration in the first place when we can just offer an iterator API? We really don't want to be making system calls here +1.
