### ISSUE TITLE
Restructure chain data indexing

### ISSUE THREAD

**Issue by evanlinjin** [LLFourn/bdk_core_staging#32]
Here are our current components:

1. SparseChain: It indexes transactions and where they are in blocks.
2. SpkTracker: It indexes txouts by script pubkeys in whatever transactions you add to it.

## Design goals

1. We want to be able to incrementally update `SpkTracker` with new data in the blockchain where complexity proportional to the changes (e.g. number of new transactions) since `SpkTracker` was last updated. This currently works but only in the case that new transactions are all later in the blockchain than when it was last updated.

2. We want to able to update the list of TXIDs in our TXID set in `SparseChain` without necessarily getting the full transaction data. Suggestion: split sprase chain into a (i) monotone structure which just stores and indexes transactions (but doesn't know which in the chain or not) and (ii) a non-monotone structure which keeps track of where transactions are in the chain but doesn't have full transaction data. We want to be able to quickly find which txids exist in the non-monotone structure but not in the monotone one.

3. `SpkTracker` currently has to scan over all the txouts to find which are unspent. We should be able to create an index of this. Preferably, this would be outside `SpkTracker`. Something like an `UnspentIndex`. `UnspentIndex` would be non-montone and would require the non-monotone blockchain data to generate.

## Potential Solution

1. Do not rely on the order of transactions in updates like the checkpointing system does. Rather, just cache the updates to each structure and then when other structures need to sync to it they can recall which was the last update they saw i.e. like git commits and merging.

## Potential Order

1. Purge codebase of internal checkpointing logic. `CheckPointCandidate` doesn't need to be changed here just the internal optimizing algorithms in `SpkTracker` and `SparseChain`.
2. Split `SparseChain` into monotone and non-monotone structures. Also change `CheckPointCandidate` to only have `txids` rather than full transactions.
3. Add commit like indexing from `SpkTracker` to monotone `SparseChain` and from monotone `SparseChain` to non-monotone `SparseChain`. (rename these monotone `SparseChain` could `TxGraph`).
4. Develop `UnspentIndex`.

**Comment by LLFourn** [comment]
This looks good but actually I might swap 3 and 4 so APIs are solid first and then use commit structure to optimize.

**Comment by evanlinjin** [comment]
TODO:

- [ ] Do we need marker type to enforce blocktime of tx?

**Comment by evanlinjin** [comment]
# To Do (2)
- [ ] API to add auxiliary transactions to the mempool
- [ ] Implement ability to move all invalidated transactions to mempool and check for consistency when we invalidate blocks.

**Comment by LLFourn** [comment]
This seems to be done. I'll open up a new issue for unspent index.
