### ISSUE TITLE
Improve signature of `CoinSelectorOpt::fund_outputs`

### ISSUE THREAD

**Issue by evanlinjin** [LLFourn/bdk_core_staging#33]
```rust
pub fn fund_outputs(txouts: &[(Script, u64)], drain_output: &Script, ...)
```

This potentially will be better.

**Comment by evanlinjin** [comment]
@rajarshimaitra

**Comment by LLFourn** [comment]
What's wrong with `TxOut` type? I get that the `drain_output` we don't need to know the value so +1 there.

**Comment by evanlinjin** [comment]
> What's wrong with `TxOut` type? I get that the `drain_output` we don't need to know the value so +1 there.

@LLFourn good point. Let's just change the second input then to `drain_script`.

**Comment by LLFourn** [comment]
Let's close this since my PR #46  already changes this API
