### ISSUE TITLE
Use error deriving macro

### ISSUE THREAD

**Issue by rajarshimaitra** [LLFourn/bdk_core_staging#5]
At some point we will need proper Error structure for the `bdk_core` lib. 

This is a tracking issue on discussing over the possible `Error` struct.

**Comment by LLFourn** [comment]
I want to avoid a single `Error` struct in `bdk_core`. Most functions should be error free. Every function that is fallible should have its own error type. On the error front I do want to avoid all the boilerplate involved in errors by maybe adding a dep on https://github.com/yaahc/displaydoc or something similar.

**Comment by LLFourn** [comment]
@rajarshimaitra yeah the reason I didn't use thiserror is because it's not `no_std` compatible I think. We should try displaydoc first. I don't think we'll need `anyhow` here in the main `bdk_core` crate. Some of the other crates might use it.

**Comment by LLFourn** [comment]
It seems like we're just going with implementing Display manually to avoid deps. I guess we're all ok with that approach?

**Comment by rajarshimaitra** [comment]
I am still using `anyhow` for the example codes.. To me it makes sense to have dedicated error structures in `bdk_core` and agreed that `thiserror` dep should not be required.. 

But for example crates I think `anyhow` doesn't hurt and reduces boilerplate a lot..

**Comment by LLFourn** [comment]
Yep `anyhow` should be used pretty much always in any application IMO. But for `bdk_core` we can go with the minimal approach.
