### ISSUE TITLE
Add Coin Selection Algorithm

### ISSUE THREAD

**Issue by rajarshimaitra** [LLFourn/bdk_core_staging#6]
The `CoinSelectOpt` should have an enum with various algorithm options to use for coin selection.

Initial target is to cover what bdk already covers..  Largest first, Oldest first and Branch and bound.. 

This can be a potentially "good first issue" too..

**Comment by LLFourn** [comment]
The `CoinSelector` is not a coin selection algorithm it is a tool for implementing coin selection algorithms. Any particular algorithm would call functions on `CoinSelector` to keep track of how close it is to completing. Does this make sense? You're not the first person to be confused by this.

**Comment by evanlinjin** [comment]
> The `CoinSelector` is not a coin selection algorithm it is a tool for implementing coin selection algorithms. Any particular algorithm would call functions on `CoinSelector` to keep track of how close it is to completing. Does this make sense? You're not the first person to be confused by this.

Would `CoinSelectParams` be a better name?

**Comment by rajarshimaitra** [comment]
> Any particular algorithm would call functions on CoinSelector to keep track of how close it is to completing.

Yes I was indeed confused then.. So the `CoinSelector` stuffs are essentially agnostic to any algorithm.. Yes I think that makes sense..

**Comment by LLFourn** [comment]
I think `CoinSelectorOpt` make sense because they are optional parameters. "Params" I would use if they were a bunch of mandatory things that needed to be passed to something.
