### ISSUE TITLE
ChainGraph API for electrum

### ISSUE THREAD

**Issue by LLFourn** [LLFourn/bdk_core_staging#72]
1. We want to have the chaingraph enforce that for every txid in `sparse_chain` there is a full tx in the `graph`. To do this we'll have to make those fields private and we'll have to have an error case when the changeset is applied.
2. Electrum needs to fetch incrementally. First it tells you txids you are interested in (associated with your script pubkeys) and then you batch fetch the transactions. We need an API to do this. It makes sense for electrum to return something like a `SparseChain` from the first requests for related txids to the scripts. We then need to turn the txids we're missing into full transactions in a `ChainGraph` that can be applied. Hint: maybe we can have a `missing` function on `ChainGraph` that somehow returns what's missing and then a method on the electrum API to take that set of missing things and turn it into a `ChainGraph` with a batch request.

**Comment by rajarshimaitra** [comment]
I am working on this next..

**Comment by LLFourn** [comment]
Side note this means removing `insert_txid` from chain graph since this is incompatible with this design.

**Comment by LLFourn** [comment]
@evanlinjin I think we should provide this guarantee as the API can result in unintentional unwraps when you think a full tx should be there but it isn't. For electrum I don't think the update process should start with a `ChainGraph` at all:

1. grab txids of given script pubkeys.
2. Figure out which of these we need full transactions for i.e. return something like a `HashSet<Txid>` or maybe a `Vec<(Txid, I)>` where `I` is `TxHeight` in this case.
3. Fetch those full transactions and transform them into `ChainGraph<TxHeight>` with only the transactions in missing set.
4. Apply the `ChainGraph`.

**Comment by evanlinjin** [comment]
@LLFourn what about transactions being confirmed? Because they might already exist in the mempool of the original chain

**Comment by LLFourn** [comment]
@evanlinjin the update `ChainGraph<TxHeight>` will have the updated height of the transactions. I don't see a problem. The `TxHeight` of the transaction in the original chain is ignored as part of this. We only care whether it is present in the original `ChainGraph` or not.

**Comment by LLFourn** [comment]
The best way to go about this might be to do electrum with the current API first. It's not too hard to figure out which transactions are missing and you need to fetch with the current API. Once we can see what that looks like we can try and optimize both the electurm API and the chaingraph API to make it simple to document and explain,

**Comment by rajarshimaitra** [comment]
For ref, I tried the electrum sync with existing API in #77 ..
